; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino

; Serial monitor options
monitor_speed = 115200
monitor_filters = esp8266_exception_decoder

; Build options
build_flags = 
    -O2
    -DUSB_SERIAL
    -DLAYOUT_US_ENGLISH

; Upload options
upload_protocol = teensy-gui

; Library dependencies
; TODO: Add IMU library when actual sensor is selected
; lib_deps = 
;     adafruit/Adafruit MPU6050
;     adafruit/Adafruit Unified Sensor
